name: MMOCore-Power
version: '1.0'
main: org.justforfun.Main
api-version: '1.20'
depend: [PlaceholderAPI]
commands:
  mmocore-power:
    description: Reload the MMOCorePower plugin configuration.
    permission: mmocorepower.reload
    permission-message: You do not have permission to use this command.
permissions:
  mmocorepower.reload:
    description: Allows the user to reload the MMOCorePower plugin configuration.
    default: op